language: node_js
sudo: false
node_js:
- '10'
- '12'
deploy:
  provider: npm
  email: npm@muffinresearch.co.uk
  api_key:
    secure: VWARblBsd9uRP9DYw0ky2pf0PbzlNouElpNT9YbMiYiQmr05i2c1JTfLDIRWAHsEG1/OGnL/f6AfO98HVoJQfTRk7CalDPiOBUEo9WpSi9jkwVLcekYZ06b4rgKPYmq1u6A3YgSrpBzMpSw2eUyIDEgDXZJEk1tWFKRL/69E4HE=
  on:
    tags: true
    repo: muffinresearch/payment-icons
script:
- yarn run test-ci
